#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Load nvm and use the version specified in .nvmrc
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Use the Node version from .nvmrc
nvm use

yarn lint
